data_path: DATA_PATH
model_path: MODEL_PATH

n_predictions: 0 # 0
resume: false

n_epochs: 100
batch_size: BATCH_SIZE
augmentation_probability: 0
augmentation_strategy: all

vocabulary_path: VOCABULARY_PATH
output_directory: OUTPUT_DIRECTORY
task: forward_prediction
