data_path: DATA_PATH
model_path: MODEL_PATH

n_predictions: 0 # 0
resume: false

n_epochs: 40
batch_size: BATCH_SIZE
augmentation_probability: 0
augmentation_strategy: all # Can be set to "all", "reactants", "products" when using synthesis datamodule

vocabulary_path: VOCABULARY_PATH
output_directory: OUTPUT_DIRECTORY
task: forward_prediction



# masker:
#   type: SpanTokensMasker  # SpanTokensMasker, ReplaceTokensMasker
#   arguments:
#    - mask_prob: 0

# model_hyperparams:
#   optimizer:
#     learning_rate: 0.005
