data_path: DATA_PATH
model_path: MODEL_PATH

n_predictions: 1
resume: false

n_epochs: 100
batch_size: BATCH_SIZE
augmentation_probability: 0.5
augmentation_strategy: all

vocabulary_path: VOCABULARY_PATH
output_directory: OUTPUT_DIRECTORY
task: backward_prediction
