data_path: DATA_PATH
model_path: MODEL_PATH

resume: false

n_epochs: 300
batch_size: BATCH_SIZE
augmentation_probability: 0
augmentation_strategy: all # Can be set to "all", "reactants", "products" when using synthesis datamodule

vocabulary_path: VOCABULARY_PATH
output_directory: OUTPUT_DIRECTORY
task: forward_prediction

acc_batches: 8
check_val_every_n_epoch: 3

# masker:
#   type: SpanTokensMasker  # SpanTokensMasker, ReplaceTokensMasker
#   arguments:
#    - mask_prob: 0


model_hyperparams:
  optimizer:
    learning_rate: 1.0
  
