data_path: DATA_PATH
model_path: MODEL_PATH

resume: false

n_epochs: 500
batch_size: BATCH_SIZE
augmentation_probability: AUGMENTATION_PROBABILITY
augmentation_strategy: all # Can be set to "all", "reactants", "products" when using synthesis datamodule

masker:
  type: SpanTokensMasker  # SpanTokensMasker, ReplaceTokensMasker
  arguments:
   - mask_prob: MASK_PROBABILITY

vocabulary_path: VOCABULARY_PATH
output_directory: OUTPUT_DIRECTORY
task: forward_prediction

seed: 1

# acc_batches: 8
check_val_every_n_epoch: 3

datamodule:
  type: SynthesisDataModule

n_predictions: 0
# scorers:
#   - FractionInvalidScore

# model_hyperparams:
#   optimizer:
#     learning_rate: 0.5
  
